[package]
name = "protocol-cosmwasm"
version = "0.1.0"
authors = ["guorong <dudurong009@gmail.com>"]
edition = "2021"
description = "Common helpers for protocol-cosmwasm"


[dependencies]
cosmwasm-std = {version="0.13.2",default-features = false}
schemars = {version="0.7",default-features = false}
serde = { version = "=1.0.127", default-features = false, features = ["derive"] }
thiserror = {version="=1.0.30",default-features = false}

ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bn254 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-crypto-primitives = { version = "^0.3.0", default-features = false }

arkworks-setups = { path = "../arkworks-setups", default-features = false }
arkworks-native-gadgets = { path = "../arkworks-native-gadgets", default-features = false }

# curves
ark-ed-on-bn254 = { version = "^0.3.0", default-features = false }
plonk-circuits = { path = "../plonk-circuits", default-features = false }
arkworks-utils = { path = "../arkworks-utils", default-features = false }

[dev-dependencies]
hex = "0.4"
plonk-core = { path = "../plonk-core", default-features = false }
plonk-gadgets = { path = "../plonk-gadgets",  default-features = false }





