[package]
name = "protocol-cosmwasm"
version = "0.1.0"
authors = ["guorong <dudurong009@gmail.com>"]
edition = "2021"
description = "Common helpers for protocol-cosmwasm"


[dependencies]
cw20 = "0.5.0"
cw20-base = { version = "0.5.0", features = ["library"] }
cosmwasm-std = "0.13.2"
schemars = "0.7"
serde = { version = "=1.0.127", default-features = false, features = ["derive"] }
thiserror = "=1.0.30"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }

ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bn254 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-crypto-primitives = { version = "^0.3.0", default-features = false }

arkworks-setups = { path = "../arkworks-setups", default-features = false }
arkworks-native-gadgets = { path = "../arkworks-native-gadgets", default-features = false }

# curves
ark-ed-on-bn254 = { version = "^0.3.0", default-features = false }
plonk-circuits = { path = "../plonk-circuits", default-features = false }
arkworks-utils = { path = "../arkworks-utils", default-features = false }

[dev-dependencies]
hex = "0.4"
plonk-core = { path = "../plonk-core", default-features = false }
plonk-gadgets = { path = "../plonk-gadgets",  default-features = false }





