[package]
name = "protocol-cosmwasm"
version = "0.1.0"
authors = ["guorong <dudurong009@gmail.com>"]
edition = "2021"
description = "Common helpers for protocol-cosmwasm"


[dependencies]
cw20 = "0.5.0"
cw20-base = { version = "0.5.0", features = ["library"] }
cosmwasm-std = "0.13.2"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }

ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bn254 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-crypto-primitives = { version = "^0.3.0", features = ["r1cs"], default-features = false }

arkworks-setups = { version = "1.0.0", features = ["r1cs"], default-features = false }
arkworks-native-gadgets = { version = "1.0.0", default-features = false }

ark-ec = { version = "^0.3.0", default-features = false }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }

arkworks-plonk-gadgets = { path = "../arkworks-plonk-gadgets",  default-features = false }

plonk-core = { path = "../plonk-core", features = ["trace"], default-features = false }
ark-poly-commit = { version = "^0.3.0", default-features = false }
ark-poly = { version = "^0.3.0", default-features = false }

# curves
ark-ed-on-bn254 = { version = "^0.3.0", default-features = false }
plonk-hashing = { path = "../plonk-hashing" }
getrandom = { version = "0.2", features = ["js"] }
arkworks-plonk-circuits = { path = "../arkworks-plonk-circuits" }

[dev-dependencies]
hex = "0.4"


[dev-dependencies.arkworks-utils]
version = "1.0.0"
default-features = false
features = ["poseidon_bn254_x5_3"]

[features]
default = ["std"]
std = [
    "ark-std/std",
    "arkworks-native-gadgets/std",
    "ark-ff/std",
    "ark-ec/std",
]


