[package]
name = "plonk-circuits"
version = "1.0.0"
authors = ["Webb Developers"]
edition = "2021"
description = "Webb protocol's plonk zero-knowledge circuits written using Arkworks (ark-plonk)"
license = "Apache-2.0"
repository = "https://github.com/webb-tools/arkworks-gadgets"
homepage = "https://webb.tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arkworks-native-gadgets = { version = "=1.0.0", default-features = false }
plonk-gadgets = { path = "../plonk-gadgets", version = "1.0.0", default-features = false }

plonk-core = { path = "../plonk-core", features = ["trace"], default-features = false }
ark-ff = { version = "=0.3.0", default-features = false }
ark-std = { version = "=0.3.0", default-features = false}
ark-poly-commit = { version = "=0.3.0", default-features = false }
ark-poly = { version = "=0.3.0", default-features = false }
ark-ec = { version = "=0.3.0", default-features = false }
ark-serialize = { version = "=0.3.0", default-features = false }

[dev-dependencies]
# curves
ark-ed-on-bn254 = { version = "=0.3.0", default-features = false }
ark-bn254 = { version = "=0.3.0", default-features = false, features = [ "curve" ] }

[dev-dependencies.arkworks-utils]
version = "1.0.0"
default-features = false
features = ["poseidon_bn254_x5_2", "poseidon_bn254_x5_3", "poseidon_bn254_x5_4", "poseidon_bn254_x5_5"]

[features]
default = ["std"]
std = [
    "ark-std/std",
    "arkworks-native-gadgets/std",
    "plonk-gadgets/std",
    "ark-ff/std",
    "ark-ec/std",
    "ark-poly-commit/std",
    "ark-poly/std",
]
