[package]
name = "arkworks-setups"
version = "1.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Webb protocol's API for zero-knowledge circuits"
repository = "https://github.com/webb-tools/arkworks-gadgets"
homepage = "https://webb.tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arkworks-native-gadgets = { path = "../arkworks-native-gadgets",  default-features = false }
ark-crypto-primitives = { version = "^0.3.0", default-features = false }
ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
arkworks-utils = { path = "../arkworks-utils", default-features = false, features = ["poseidon_bn254_x5_3"] }


[features]
default = ["std"]
std = [  
  "arkworks-native-gadgets/std",
  "ark-crypto-primitives/std",
  "ark-ff/std",
  "ark-std/std",    
  "arkworks-utils/std",  
]
parallel = [
  "ark-crypto-primitives/parallel",
  "ark-std/parallel",    
  "ark-ff/parallel",  
  "arkworks-native-gadgets/parallel",
]

